version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "axios"
      - dependency-name: "form-data"
      - dependency-name: "lodash"
      - dependency-name: "undici"
