export enum Resource {
	ME = 'Me',
	MY = 'My',
	CONTACT = 'Contact',
	ROOM = 'Room',
}

export enum RoomOperations {
	GET_ALL = 'getAll',
	GET_DETAIL = 'getDetail',
	UPDATE_INFO = 'updateInfo',
	LEAVE_OR_DELETE = 'leaveOrDelete',
	GET_MEMBERS = 'getMembers',
	CHANGE_MEMBERS = 'changeMembers',
	GET_MESSAGES = 'getMessages',
	SEND_MESSAGE = 'sendMessage',
	GET_MESSAGE = 'getMessage',
	UPDATE_MESSAGE = 'updateMessage',
	DELETE_MESSAGE = 'deleteMessage',
	GET_TASKS = 'getTasks',
	GET_TASK = 'getTaskDetail',
	UPDATE_TASK_STATUS = 'updateTaskStatus',
	CREATE_TASK = 'createTask',
	GET_FILES = 'getFiles',
	GET_FILE = 'getFile',
	UPLOAD_FILE = 'uploadFile',
	MARK_AS_READ = 'markAsRead',
	MARK_AS_UNREAD = 'markAsUnread',
	CREATE = 'create',
	GET_LINK = 'getInviteLink',
}
